### ISSUE TITLE
install_extra_packages doesn't exist

### ISSUE THREAD

**Issue by jamesbeedy** [battlemidget/juju-layer-nginx#7]
https://github.com/battlemidget/juju-layer-nginx/blob/master/lib/charms/layer/nginx.py#L50

**Comment by adam-stokes** [comment]
We need to make use of the apt layer

**Comment by lazypower** [comment]
@battlemidget - I dont really know why we are exposing _yet another_ means of installing packages. Installing packages is already a well known and understood paradigm in charming:
- apt layer
- layer options of layer-basic
- plain old charmhelpers.fetch.apt_install
- subprocess.check_call(['apt', 'install', 'mything'])

is it necessary to support package installation from a .toml file?

**Comment by adam-stokes** [comment]
nope i want to move it to the apt layer

**Comment by lazypower** [comment]
This was closed with #10 i believe

**Comment by adam-stokes** [comment]
Yea thanks
